### PR TITLE
Fix type hints for 'ids' type (fix #49)

### LINKED ISSUE #49: Incorrect type hints for encode_ids*
The functions such as `encode_ids` and `encode_ids_with_bos_eos` returns piece ids as `int`s. But the type annotations say `-> Union[Sequence[str], Sequence[Sequence[str]]]`.
This causes warnings in PyCharm.

### PR DESCRIPTION
**Pull request by cosine0**
Fix #49

### CODE REVIEW

**Comment by bheinzerling** [comment]
Thanks!

**Comment by cosine0** [comment]
@bheinzerling Can you attach a label named `hacktoberfest-accepted` to this? I'm participating [Hacktoberfest](https://hacktoberfest.digitalocean.com/details#details). =)

**Comment by bheinzerling** [comment]
Sure, no problem. If I understand correctly, the repository also needs to have "hacktoberfest" as a topic, so I added it just in case.

**Comment by cosine0** [comment]
It counted. Thanks!

**Pull request merged**
